export const genresData = [
  {name: 'Биография', value: 'biography', icon: './biography.svg'},
  {name: 'Боевики', value: 'action', icon: './gun.svg'},
  {name: 'Детективы', value: 'detective', icon: './detective.svg'},
  {name: 'Для детей', value: 'children', icon: './child.svg'},
  {name: 'Документальные', value: 'documentary', icon: './documentary.svg'},
  {name: 'Драмы', value: 'drama', icon: './drama.svg'},
  {name: 'Зарубежные', value: 'foreign', icon: './foreign.svg'},
  {name: 'Исторические', value: 'historical', icon: './historical.svg'},
  {name: 'Комедии', value: 'comedy', icon: './comedy.svg'},
  {name: 'Криминал', value: 'crime', icon: './crime.svg'},
  {name: 'Мелодрамы', value: 'melodrama', icon: './melodrama.svg'},
  {name: 'Русские', value: 'russian', icon: './russian.svg'},
  {name: 'Приключения', value: 'adventures', icon: './adventure.svg'},
  {name: 'Семейные', value: 'family', icon: './family.svg'},
  {name: 'Советские', value: 'soviet', icon: './soviet.svg'},
  {name: 'Спорт', value: 'sport', icon: './sport.svg'},
  {name: 'Триллеры', value: 'thriller', icon: './thriller.svg'},
  {name: 'Фантастика', value: 'fantastic', icon: './fantastic.svg'},
  {name: 'Фэнтези', value: 'fantasy', icon: './fantasy.svg'}
]